### ISSUE TITLE
What about node.js section in knowledge-database?

### ISSUE THREAD

**Issue by perzanko** [HealthTechDevelopers/playbook#12]
My proposals:
- frameworks
- nice libs (https://github.com/sindresorhus/awesome-nodejs)
- tools
- ~~books, videos, articles~~
- books
- videos
- articles
- design patterns

**Comment by perzanko** [comment]
cc: @AdriannaJedrzejczak @ctomasz

**Comment by pokorson** [comment]
I think it was left since we were never seriously teaching nodeJS stuff to anyone, but it's definitely good addition. Are you up for preparing initial PR?

**Comment by ctomasz** [comment]
@perzanko if you do not mind - please, split the "_books, videos, articles_" to separate categories.

**Comment by pokorson** [comment]
@ctomasz @perzanko I think in other documents we kept convention to organise material around topic ex. React Redux - and here all articles/videos/podcasts about redux in react. Also I wonder about storing books here as library is partially stored in printed form in main office so I thought for managing books we will use 
- spreadsheet - for keeping list in single place, mark what you borrow in given time.
- google drive - for storing ebooks and pdfs

**Comment by perzanko** [comment]
@pokorson I really love organizing materials around a specific topic 
What do you think about not separating into categories, but describing each link in a few words?
i.e. 
```markdown
https://medium.com/@me_37286/19-ways-to-become-a-better-node-js-developer-in-2019-ffd3a8fbfe38 - hot topics in 2019 that you should know as node.js developer
```

**Comment by pokorson** [comment]
sounds good 👍 also with markdown we can hide url under just name

**Comment by perzanko** [comment]
Oh, yup. I've forgotten about it:
```markdown
- [Hot topics in 2019 that you should know as node.js developer](https://medium.com/@me_37286/19-ways-to-become-a-better-node-js-developer-in-2019-ffd3a8fbfe38)
```

**Comment by perzanko** [comment]
Oh, yup. I've forgotten about markdown.. Let's add label to this link too!

- [[Article] Hot topics in 2019 that you should know as node.js developer](https://medium.com/@me_37286/19-ways-to-become-a-better-node-js-developer-in-2019-ffd3a8fbfe38)

**Comment by perzanko** [comment]
opened PR for this: https://github.com/HealthTechDevelopers/playbook/pull/15.
Feel free to suggest something
