### ISSUE TITLE
What is playbook/coder-reviews.md?

### ISSUE THREAD

**Issue by perzanko** [HealthTechDevelopers/playbook#18]
@maciej-zywno , should we update this document and describe *code review* process?

**Comment by maciej-zywno** [comment]
@perzanko Yes. And we can keep the four links I listed there as a "Bibliografia"

**Comment by perzanko** [comment]
Here is the `code review` section - https://github.com/HealthTechDevelopers/playbook/blob/master/workflow-guideline.md.

I think we need to move it to separate doc.

**Comment by pokorson** [comment]
I would keep it in single doc until workflow guideline grew really big 👍

**Comment by pokorson** [comment]
also It's not written anywhere yet but I recommend for each project/team to have it's own workflow guideline and playbook document serve as reference of good practices for such guideline

**Comment by pokorson** [comment]
@perzanko https://github.com/HealthTechDevelopers/playbook/pull/35

**Comment by perzanko** [comment]
closed in #35
