### ISSUE TITLE
Async communication & slack culture guide

### ISSUE THREAD

**Issue by pokorson** [HealthTechDevelopers/playbook#23]
@perzanko @maciej-zywno @dskoneczny do you think such document could be useful?

**Comment by perzanko** [comment]
We could describe the purposes of slack channels. What do u mean 'slack culture guide'? 🤓

**Comment by pokorson** [comment]
stuff like using threads for single topic discussions, professional language, list of english only channels, no spamming in public channels, thinking twice before using `@here` `@channel` mentions, existing slack groups

**Comment by perzanko** [comment]
![sword](https://user-images.githubusercontent.com/22469100/53946841-df8f7800-40c4-11e9-9b83-f59afb0c0a7b.jpg)

**Comment by sciolkowski** [comment]
![image](https://user-images.githubusercontent.com/9269165/53949999-7b23e700-40cb-11e9-875a-70c90bedb9de.png)
