### ISSUE TITLE
Onboarding tech materials

### ISSUE THREAD

**Issue by pokorson** [HealthTechDevelopers/playbook#24]
We could extract separate page with resources for first month in HTD for student newcomers.
- Anything about basic programming skills ex. Clean Code book
- Category list for materials in each technology - JS, Ruby/Ror, TS, React, Python, Git

**Comment by perzanko** [comment]
Maybe we'll just use the knowledge database for that purpose

**Comment by pokorson** [comment]
@perzanko yes, but I still think it would be good to have single document in knowledge database.

**Comment by perzanko** [comment]
maybe a separate section in each document, eg 'Onboarding' and linking from this single one that you propose

**Comment by perzanko** [comment]
I would rather have one place where materials are collected around the domain I am interested in, e.g. Node.js

**Comment by pokorson** [comment]
Idea is to give easier access to those materials as they will definitely touch different areas. Otherwise we're forcing them to jump across entire knowledge base while they need only small subset of it

**Comment by pokorson** [comment]
@dskoneczny do you know what's the state of technical onboarding? Is there some action to be done or is this already taken care of and we can close the issue?
