### ISSUE TITLE
Team's Skill Book

### ISSUE THREAD

**Issue by perzanko** [HealthTechDevelopers/playbook#25]
## Problem:
Sometimes it happens that we don't know exactly how to do something or we have problems with something, and then we ask someone from the team for advice. The task is a bit difficult when we don't know what individual members do and what they are good at. (eg Newcomers)

## Proposal
Team's Skill Book - a list of people in the company with descriptions of what they do. The description could contain such items as:
- areas in which the person works (backend, frontend, mobile, management, HR, etc.)
- projects the person is working on
- skills, eg (native english, soft communication skills, AWS)
- programming languages
- frameworks etc ..

We could create a separate document within playbook. @pokorson what do u think?

**Comment by pokorson** [comment]
that could be definitely useful, it somehow corelates with trello board Patrycja created. However I would reverse the list grouping. First technologies and then list of people you may ask questions about it.

**Comment by perzanko** [comment]
it would be more technology-oriented 🤓

**Comment by jablonskipj** [comment]
@perzanko @pokorson do you also consider putting here info about libraries commonly used by the developer or this is too specific? I can see the advantage of this when someone is looking for very specific kind of problem which SO/google/blogs/etc. is not able to clarify.

**Comment by pokorson** [comment]
let's start with top level technologies and see how it goes

**Comment by perzanko** [comment]
I think we should prepare a survey. Who wants to do it?

**Comment by pokorson** [comment]
It became a bit stale so small update from my side:
I'm thinking of solution which will be more flexible and allow us to create profiles for HTD employees. Covering both tech skills side and all personal info currently kept in trello board

**Comment by perzanko** [comment]
Trello Board does the job for now. If anyone wants to extend the Trello Board, he should do it there. Closing 🤓
